import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {useState} from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Collins Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>developedbycollo</h1>
            <ul className='flex items-center'>
              <li className='dark:text-white'>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-2xl'/>
              </li>
              <li className=' bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 rounded-md ml-8'>
                <a href="#">Resume</a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white'>Collins Kaiser</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur delectus, nesciunt quis ad dolor 
              aperiam animi vero fuga iusto corrupti voluptatibus mollitia voluptates ullam itaque laboriosam nam, minima reiciendis veniam.</p>
          </div>
          <div className='text-5xl flex justify-center gap-12 py-3 text-gray-600'>
              <AiFillTwitterCircle/>
              <AiFillLinkedin/>
              <AiFillInstagram/>
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover'/>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi adipisci, <span className='text-teal-500'>molestiae</span> quae ipsa explicabo distinctio tempore, odit illum laborum fugit voluptas 
              nihil non, similique voluptate optio? Rem <span className='text-teal-500'>molestiae</span> harum quibusdam.
            </p>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque autem officiis id similique nam alias accusamus placeat fugiat ratione tempore dignissimos 
              ipsa ab quaerat, rerum corporis, <span className='text-teal-500'>molestiae</span> veniam vitae dolorum aliquid.
            </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Best Designs</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam numquam libero atque nostrum labore est id, quibusdam fugit velit asperiores dolorem 
                nulla at cum dicta voluptatum. Praesentium modi asperiores neque.
              </p>
              <h4 className='py-4 text-teal-600'>My Design Tools</h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>PhotoShop</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Best Designs</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam numquam libero atque nostrum labore est id, quibusdam fugit velit asperiores dolorem 
                nulla at cum dicta voluptatum. Praesentium modi asperiores neque.
              </p>
              <h4 className='py-4 text-teal-600'>My Design Tools</h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>PhotoShop</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Best Designs</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam numquam libero atque nostrum labore est id, quibusdam fugit velit asperiores dolorem 
                nulla at cum dicta voluptatum. Praesentium modi asperiores neque.
              </p>
              <h4 className='py-4 text-teal-600'>My Design Tools</h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>PhotoShop</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>
              Portofolio
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi adipisci, <span className='text-teal-500'>molestiae</span> quae ipsa explicabo distinctio tempore, odit illum laborum fugit voluptas 
              nihil non, similique voluptate optio? Rem <span className='text-teal-500'>molestiae</span> harum quibusdam.
            </p>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque autem officiis id similique nam alias accusamus placeat fugiat ratione tempore dignissimos 
              ipsa ab quaerat, rerum corporis, <span className='text-teal-500'>molestiae</span> veniam vitae dolorum aliquid.
            </p>
          </div>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>

    </div>
  );
}
